FROM markllama/pulp-base
MAINTAINER Mark Lamourine <markllama@gmail.com>

# Define and export the Pulp content locations
VOLUME ["/var/www", "/var/lib/pulp"]

# Run a command that indicates (trivial) success and exits
CMD ["/bin/true"]
