apiVersion: v1beta3
kind: Service
metadata:
  name: pulp-web
spec:
  ports:
  - name: http-tcp
    port: 80
  - name: https-tcp
    port: 443
  publicIPs:
  - $public_ip
  selector:
    name: pulp-web
