= MongoDB for Pulp

This http://docker.com[Docker] image provides a self contained http://mongodb.org[MongoDB] service for Pulp. For the moment this is a custom container image, but the plan is to migrate to a stock one when one becomes available. We need to determine the means to create a re-usable container service that can be used by any mongo client, but which can be labeled and discovered within http://github.com/GoogleCloudPlatform[Kubernetes].

== Image Details

The image spec here is based on Fedora 21 x86_64. 

== Stock Alternatives
A  http://gitub.com/goern/mongodb[replacement candidate] is defined by Christoph Goern, designed for use within OpenShift.  As a reusable image candidate this is a good place to start.  That image is available on DockerHub:

    docker search  openshift/mongodb-24-centos7
    NAME                           DESCRIPTION                                     STARS     OFFICIAL   AUTOMATED
    openshift/mongodb-24-centos7   A Centos7 based MongoDB v2.4 image for use...   0                    

Note both that this alternate image is based on CentOS 7 and that this shouldn't matter one wit.

