apiVersion: v1beta3
kind: ReplicationController
metadata:
  name: pulp-apache-rc
spec:
  replicas: 1
  template:
    metadata:
      labels:
        name: pulp-web
      name: pulp-apache
    spec:
      containers:
      - capabilities: {}
        image: $image
        name: pulp-apache
        ports:
        - containerPort: 80
          protocol: TCP
        - containerPort: 443
          protocol: TCP
        env:
        - name: PULP_SERVER_NAME
          value: pulp.example.com
        - name: SSL_TARBALL_URL
          value: http://refarch.cloud.lab.eng.bos.redhat.com/pub/users/mlamouri/apache_ssl_keys.tar
        volumeMounts:
        - mountPath: /dev/log
          name: devlog
        - mountPath: /var/www
          name: varwww
        - mountPath: /var/lib/pulp
          name: varlibpulp
      restartPolicy: Always
      volumes:
      - hostPath:
          path: /dev/log
        name: devlog
      - hostPath:
          path: /opt/pulp/var/www
        name: varwww
      - hostPath:
          path: /opt/pulp/var/lib/pulp
        name: varlibpulp
